### ISSUE TITLE
Getting error while calculating chunks size and summing up it to bytes and checkin its size

### ISSUE THREAD

**Issue by TAMILVIP007** [DjDeveloperr/ytdl_core#7]
https://stackoverflow.com/questions/74752865/getting-error-while-calculating-chunks-size-and-summing-up-it-to-bytes-and-check?noredirect=1#comment131944020_74752865

**Comment by DjDeveloperr** [comment]
Try importing ytld core from this commit: https://raw.githubusercontent.com/DjDeveloperr/ytdl_core/508bcb1a2a386de475a6bd3348ce7b2e6b1ca2af/mod.ts

**Comment by Mysterio-cell** [comment]
okie i ran `deno cache --reload file.ts` and than again tried `deno run -A file.ts`
and it partially worked it does returned big but also got error at the same tim https://nekobin.com/mufesetomi

**Comment by DjDeveloperr** [comment]
I see the stack trace still points to module at deno.land. The fix is not out yet, I suggested trying the fix I implemented in recent commit.
Also, preferably post logs on GitHub itself instead of pointing to external services.

**Comment by Mysterio-cell** [comment]
> I see the stack trace still points to module at deno.land. The fix is not out yet, I suggested trying the fix I implemented in recent commit. Also, preferably post logs on GitHub itself instead of pointing to external services.

coool it works thanks can this be pushed to deno.land?

**Comment by DjDeveloperr** [comment]
Published v0.1.2
